### ISSUE TITLE
"lock deadline" show's unexpected date on mainnet

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/token-lock#13]
On Gnosis Chain, the "lock dealine" is correctly displayed as February 15th, 2022.
![image](https://user-images.githubusercontent.com/8453294/151736526-fb37e3f6-7949-4121-9107-c6e263b23d02.png)

On mainnet, the "lock deadline" is diplayed as Jan 18th, 2023.
![image](https://user-images.githubusercontent.com/8453294/151735318-70bc3ebe-07d4-418b-b149-0992e819e71b.png)

Both contracts were created using the same parameters for `lockDeadline` and `lockDuration`.

**Comment by jfschwarz** [comment]
the app was still hardcoded to Rinkeby test addresses. works now with the real addresses being configured
