### ISSUE TITLE
metamask??

### ISSUE THREAD

**Issue by samscalet** [gnosis/token-lock#35]
where metamask connect? i remember locking with metamask on this page year ago... where is it

![Screenshot-20230316155054-1184x721](https://user-images.githubusercontent.com/52046359/225550376-6b1a5ce9-9ae2-47fd-b41e-a293f2144be2.png)

**Comment by samepant** [comment]
What network are you trying to connect on? I am able to connect with Metamask on mainnet, gnosis chain and goerli.
